@define-color background #1e1e2e;
@define-color text #cdd6f4;
@define-color subtext #a6adc8;
@define-color overlay #6c7086;

@define-color active-background #6c7086;
@define-color active-foreground #313244;

@define-color hover-background #CBA6F7;
@define-color hover-foreground #313244;

@define-color pink #f5c2e7;
@define-color purple #cba6f7;
@define-color red #f38ba8;
@define-color orange #fab387;
@define-color yellow #f9e2af;
@define-color green #a6e3a1;
@define-color blue #89b4fa;
