@define-color background #1f2335;
@define-color text #a9b1d6;
@define-color subtext #c0caf5;
@define-color overlay #3b4261;

@define-color active-background #bb9af7;
@define-color active-foreground #b4f9f8;

@define-color hover-background #7aa2f7;
@define-color hover-foreground #cfc9c2;

@define-color pink #ff007c;
@define-color purple #9d7cd8;
@define-color red #c53b53;
@define-color orange #ff9e64;
@define-color yellow #ffc777;
@define-color green #c3e88d;
@define-color blue #7aa2f7;
