@define-color background #1B2A38;
@define-color text #FAFEFE;
@define-color subtext #81a9bf;
@define-color overlay #4b6772;

@define-color active-background #11b4b4;
@define-color active-foreground #ccffff;

@define-color hover-background #4b7d7d;
@define-color hover-foreground #aaf0f0;

@define-color pink #B672A6;
@define-color purple #9604ED;
@define-color red #FF2C2A;
@define-color orange #E35205;
@define-color yellow #F2E263;
@define-color green #A2D557;
@define-color blue #2069C3;
