@define-color background #191724;
@define-color text #e0def4;
@define-color subtext #908caa;
@define-color overlay #26233a;

@define-color active-background #eb6f92;
@define-color active-foreground #a1d2da;

@define-color hover-background #31748f;
@define-color hover-foreground #f6c177;

@define-color pink #eb6f92;
@define-color purple #c4a7e7;
@define-color red #b4637a;
@define-color orange #ea9d34;
@define-color yellow #f6c177;
@define-color green #56949f;
@define-color blue #3e8fb0;
